on: [push]

jobs:
  test_macos_clipboard:
    name: test clipboard functionality on macos
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: install
        run: python -m pip install --upgrade . && python -m pip install pytest

      - name: run tests
        run: python3.8 -m pytest -v

