on: [push, pull_request]

jobs:
  test_macos_clipboard:
    name: test clipboard functionality on macos
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: install
        run: python -m pip install --upgrade . && python -m pip install pytest coverage coveralls && pip install .

      - name: run tests
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: "true"
        run: coverage run -m pytest -v && coveralls --service=github

