on: [push, pull_request]

jobs:
  test_macos_clipboard:
    name: test clipboard functionality
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install -y xvfb xclip

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: install
        run: python -m pip install --upgrade . && python -m pip install pytest coverage codecov && pip install .

      - name: start-xvfb
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo Xvfb :99 -screen 0 640x480x8 -nolisten tcp &

      - name: run tests
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: "true"
          DISPLAY: ":99"
        run: coverage run -m pytest -v && codecov